import { ScratchRgsInterface, ScratchcardRgs } from './ScratchApi';
import { RgsAdapter } from './RgsAdapter';
import { SimpleFlowRgs, SimpleFlowInterface } from './SimpleFlowApi';
export default class DummyAdapter extends RgsAdapter<ScratchcardRgs | SimpleFlowRgs> implements ScratchRgsInterface, SimpleFlowInterface {
    realityCheck: boolean;
    configured: Promise<any>;
    constructor();
    getJwt(): string;
    setRealityCheck(activate: boolean): void;
    setGameMode(history: boolean): void;
    getGame(): Promise<any>;
    getStakeOptions(): number[];
    getDefaultStake(): number;
    limitStakes(limits: number[]): void;
    getAccount(): Promise<any>;
    getTicket(ticketId: string): Promise<any>;
    getUnsettledTicket(): Promise<any>;
    purchaseTicket(): Promise<any>;
    getTicketData(): Promise<any>;
    setTicketData(): Promise<any>;
    settleTicket(): Promise<any>;
    refresh(): Promise<any>;
    spin(): Promise<any>;
    freeSpin(): Promise<any>;
    close(): Promise<any>;
    getGamble(): Promise<any>;
    gamble(): Promise<any>;
    sendCustomRequest(): Promise<any>;
    getJackpots(): Promise<any>;
    getAllJackpots(): Promise<any>;
    getJackpotWins(): Promise<any>;
}
