import { RgsAdapterConfig } from './RgsAdapter';
import ScratchAdapter from './ScratchApi';
import { SlotRgsInterface } from './SlotApi';
export declare class PmrAdapter extends ScratchAdapter implements SlotRgsInterface {
    protected pendingRounds: any[];
    protected settled: boolean;
    protected ticketPrice: number;
    protected winAmount: number;
    protected currency: string;
    protected playerId: string | null;
    protected balanceAfterPurchase: number | undefined;
    protected settledBalance: number | undefined;
    protected lineCount: number | undefined;
    protected betMult: number;
    private firstTimeExecuted;
    constructor(config: RgsAdapterConfig);
    getAccount(fromJwt?: boolean): Promise<any>;
    protected resolveBetMultiplier(): number;
    protected engineGameName(): string;
    spin(_lineCount: number, _gameType: string, betPerLine: number): Promise<any>;
    freeSpin(): Promise<any>;
    close(ticketId?: string): Promise<any>;
    refresh(): Promise<any>;
    getAllLines(): number[];
    getLineOptions(): number[];
    getDefaultLines(): number;
    protected captureTicket(ticket: any): void;
    protected balanceOf(ticket: any): number | undefined;
    protected revealRounds(ticket: any): any[];
    protected firstRound(rounds: any[]): any;
    protected reshapeRounds(rounds: any[]): any[];
    protected addRoundBetContext(p: any, tp: number): void;
    protected remapEntry(entry: any): void;
    protected scaleMoney(p: any, tp: number): any;
    protected scaleAtPath(root: any, path: string, tp: number): void;
    protected pathKey(t: string): string | number;
    protected finalResponse(finalBalance?: number): any;
    protected idleResponse(): any;
}
