import { CapabilitiesHost } from '../CapabilitiesHost';
import { GameClientConfig } from '../GameClient';
import { AnyObject, ConstructorOf } from '../UtilTypes';
import { RgsInterface, Rgs, RgsPlugin } from './Rgs';
import { RgsError, StakeLimits } from './RgsTypes';
export interface RgsAdapterConfig {
    gameConfig: GameClientConfig;
    gameId: string | string[];
    params: any;
    rpcUrl?: string;
    demo?: boolean;
}
export declare type RgsAdapterBaseAction = 'get-account' | 'get-ticket' | 'get-gamble' | 'gamble' | 'get-jackpots' | 'get-all-jackpots' | 'get-jackpot-wins' | 'get-jackpot-url' | 'get-bonus-offer' | 'send-custom-request';
export declare type RgsAdapterPlugin = (rgs: RgsAdapter<Rgs>, data: AnyObject) => Promise<any>;
declare type RgsAdapterAction = RgsAdapterBaseAction;
export declare class RgsAdapter<T extends Rgs> extends CapabilitiesHost implements RgsInterface {
    rgs: T;
    ticketId: string;
    readonly gameConfig: GameClientConfig;
    protected types: string[];
    protected defaultStake: number;
    protected stakeList: number[];
    protected stakeOptions: number[];
    gambleOptions: string[];
    hasGamble: boolean;
    isHistoryReplay: boolean;
    protected plugins: Record<RgsAdapterAction, RgsAdapterPlugin[]>;
    realityCheck: boolean;
    retryPurchase: (reason: RgsError, tryCount: number, args: any[]) => Promise<any>;
    protected resolveConfigured: Function;
    static blockRequests: boolean;
    static blockReason: string;
    configured: Promise<void>;
    protected resolveFinish: () => void;
    protected controlledFinishPromise: Promise<void>;
    getJwt(): string;
    setJwt(jwt: string): void;
    constructor(config: RgsAdapterConfig, RgsClass?: ConstructorOf<T>);
    protected createFinishPromise(): void;
    is<T extends RgsAdapter<Rgs>>(type: ConstructorOf<T> | string): boolean;
    applyGameConfig(): void;
    applyGameData(data: any): void;
    setRealityCheck(activate: boolean): void;
    setGameMode(isHistoryReplay: boolean): void;
    getDefaultStake(): number;
    getAllStakes(): number[];
    getStakeOptions(): number[];
    limitStakes(limits: number[]): void;
    getLimits(): {
        stakes: number[];
    };
    setLimits(limits: StakeLimits): void;
    initGame(): Promise<any>;
    purchase(...args: any[]): Promise<any>;
    feature(): Promise<any>;
    settle(): Promise<any>;
    getAccount(): Promise<any>;
    getTicket(ticketId: string): Promise<any>;
    getUnsettledTicket(): Promise<any>;
    getTicketData(ticketId?: string): Promise<any>;
    setTicketData(data: string | object, ticketId?: string): Promise<any>;
    getWalletData(): Promise<any>;
    getGambleOptions(): string[];
    getGamble(ticketId?: string): Promise<AnyObject>;
    gamble(symbol: string, ticketId?: string): Promise<AnyObject>;
    getJackpots(): Promise<AnyObject>;
    getAllJackpots(): Promise<AnyObject>;
    getJackpotWins(jackpotId: string, numberOfWins: number): Promise<AnyObject>;
    getJackpotSubscriptionUrl(): Promise<AnyObject>;
    getBonusOffer(): Promise<AnyObject>;
    sendCustomRequest(service: string, method: string, args: any[]): Promise<AnyObject>;
    protected handleError(reason: RgsError, blockReqs?: boolean): Promise<never>;
    dispatchEvent(event: string, data?: any): void;
    protected dispatchError(reason: RgsError): void;
    protected tryRetryPurchase(reason: RgsError, tryCount: number, args: any[]): Promise<any>;
}
export interface RgsMultiAdapterConfig extends RgsAdapterConfig {
    metaGameId?: string;
}
export declare class RgsMultiAdapter<T extends Rgs> extends RgsAdapter<T> {
    rgsMap: Map<string, RgsAdapter<T>>;
    protected activeAdapter: RgsAdapter<T>;
    metaGameId: string;
    bonusRoundsGameId: string;
    metaRgs: RgsAdapter<T>;
    protected subgameOptions: string[];
    constructor(config: RgsMultiAdapterConfig, RgsAdapterClass: ConstructorOf<RgsAdapter<T>>);
    applyGameConfig(): void;
    is<T extends RgsAdapter<Rgs>>(type: ConstructorOf<T> | string): boolean;
    protected updateActiveRgs: (rgs: RgsAdapter<T>, force?: boolean) => void;
    setJwt(jwt: string): void;
    setRealityCheck(activate: boolean): void;
    setGameMode(isHistoryReplay: boolean): void;
    getDefaultStake(): number;
    getAllStakes(): number[];
    getStakeOptions(): number[];
    limitStakes(limits: number[]): void;
    getAllSubgames(): string[];
    getSubgameOptions(): string[];
    setSubgameLimits(limits: string[]): void;
    getLimits(): {
        subgames: string[];
        stakes: number[];
    };
    setLimits(limits: StakeLimits): void;
    game(gameId: string): RgsAdapter<T>;
    initGame(): Promise<any>;
    purchase(...args: any[]): Promise<any>;
    feature(): Promise<any>;
    settle(): Promise<any>;
    getTicket(ticketId: string): Promise<any>;
    addRgsPluginToAllSubadapters(action: string, plugin: RgsPlugin): void;
    updateOgsRgsMap(data: any): void;
}
export {};
