import { IntegrationLogic } from '../integration-logic';
import { GameWrapperConfig } from '../../GameWrapper';
import { OgsParams, GcmCore, OptionTypes, BalanceType, FreeRoundsInfo, RgsBalance, CommonUIConfig } from "./ogs-integration-types";
import { GcmLoader } from './gcm-loader';
import { WalletMessage } from '../../rgs/WalletMessage';
import { MessageQueue } from '../../MessageQueue';
import { RgsAdapter } from '../../rgs/RgsAdapter';
import { Rgs } from '../../rgs/Rgs';
import { RgsError, StakeLimits } from '../../rgs/RgsTypes';
import { AnyObject } from '../../UtilTypes';
import Autoplay from '../../autoplay/Autoplay';
type MessageScenario = 'info' | 'lobbyDialog' | 'realityCheck' | 'replayStarted' | 'replayFinished' | 'sessionTimeout' | 'insufficientFunds' | 'invalidBetLevelFreeRound' | 'technicalError' | 'networkError';
type ScenarioStates = 'default' | 'lobbyDialog' | 'replayFinishedHistory' | 'replayFinishedLobby';
export declare class OgsIntegrationLogic extends IntegrationLogic {
    protected config: GameWrapperConfig;
    protected gcmLoader: GcmLoader;
    protected gcm: GcmCore;
    protected ogsParams: OgsParams;
    protected resolveGameFinish: () => void;
    protected scenarioState: ScenarioStates;
    protected EventWalletMessage: WalletMessage | null;
    protected walletMessages: (WalletMessage | null)[];
    protected messageQueue: MessageQueue;
    protected messageQueuePromise: Promise<any>;
    protected resolveMessageQueue: () => void;
    protected isFreeRoundsActive: boolean;
    protected isRgsGameRoundActive: boolean;
    protected isAssetsLoaded: boolean;
    protected isBalanceInitialized: boolean;
    protected isStakeInitialized: boolean;
    protected isGameReadyReceived: boolean;
    protected isGcmGameReadyCalled: boolean;
    protected realBalance: number;
    protected bonusBalance: number;
    protected unsettledTicketExists: boolean;
    init(config: GameWrapperConfig): void;
    setUnsettledTicketExists(ticketExists: boolean): void;
    updateLoadingProgress(progress: number): void;
    formatCurrency(value: number, trimFraction?: boolean, currencyCode?: string): string;
    formatNumber(value: number, trimFraction?: boolean): string;
    muteSound(mute: boolean): void;
    handleRgsError(reason: RgsError): void;
    handleReplayStarted(): Promise<void>;
    handleReplayFinished(): void;
    showError(scenario: MessageScenario | RgsError): Promise<void>;
    showInfoMessage(scenario: MessageScenario, message?: string): Promise<void>;
    protected addPromoHeader(xmlHttp: XMLHttpRequest): void;
    protected updatePromoData(jwt: string, methodName: string): void;
    protected queueMessageHandler(messageHandler: () => Promise<any>): void;
    protected getInitializationObject(): {
        getConfig: any;
        configReady: any;
        gameRevealed: any;
        gcmReady: any;
        balancesHasChanged: any;
        optionHasChanged: any;
        redirect: any;
        reload: any;
        resume: any;
        handleFreeRoundsUpdate: any;
    };
    protected getRealityCheckParams(): {
        realityCheckInfo: {
            jurisdiction: string;
            sessionTime: string;
            realityCheckPeriod: string;
            title: string;
            options: {
                proceed: {
                    label: string;
                    value: string;
                };
                exit: {
                    label: string;
                    value: string;
                };
                history: {
                    label: string;
                    value: string;
                };
            };
        };
    };
    protected getConfig(): CommonUIConfig;
    protected internalConfigReady(ogsParams: OgsParams): void;
    protected parseFreeRoundsData(): void;
    protected registerPlugins(): void;
    protected registerSupportedOptions(): Promise<void>;
    protected gameRevealed(): void;
    protected gcmReady(gcm: GcmCore): void;
    protected balancesHasChanged(balances: BalanceType): void;
    protected optionHasChanged(optionType: OptionTypes, newValue: boolean): void;
    protected redirect(redirectUrl: string): void;
    protected reload(): void;
    protected redirectToLobby(): void;
    protected resume(errorParamIndex: number): void;
    protected handleFreeRoundsUpdate(freeRoundsInfo: FreeRoundsInfo): Promise<void>;
    protected isBetAvailable(rgs: RgsAdapter<Rgs>, bet: number | number[]): boolean;
    protected getLimitsForBet(rgs: RgsAdapter<Rgs>, bet: number): StakeLimits;
    protected handleContextBalanceUpdate(rgs: RgsAdapter<Rgs>, data: AnyObject): Promise<void>;
    protected handleJwtUpdate(host: any, data: AnyObject): Promise<void>;
    protected handleNewRequest(host: any, data: AnyObject): Promise<void>;
    protected handleErrorInAutoplay(autoplay: Autoplay, data: AnyObject): Promise<void>;
    protected resolveWalletMessage(i: number): void;
    protected updateGameReadyStatus(): void;
    protected handleRgsBalanceUpdate(rgsBalance: RgsBalance): void;
    protected setEventHandlers(): void;
}
export {};
