import { IntegrationLogic } from './integration-logic';
import { GameWrapperConfig } from '../GameWrapper';
import { AnyObject, Currency } from '../UtilTypes';
import { BonusInfo } from './default-integration-types';
import { RgsAdapter } from '../rgs/RgsAdapter';
import { Rgs } from '../rgs/Rgs';
import { RgsError, StakeLimits } from '../rgs/RgsTypes';
import Autoplay from '../autoplay/Autoplay';
declare type BonusOfferFinishReason = 'bonusSpent' | 'bonusUnavailable' | 'invalidBetLevel';
export declare class DefaultIntegrationLogic extends IntegrationLogic {
    protected config: GameWrapperConfig;
    protected unsettledTicketExists: boolean;
    protected bonusInfo: BonusInfo;
    protected bonusRoundsRgs: Rgs;
    protected betLevel: number;
    protected lastShownBonusId: string | null;
    protected isUsingBonus: boolean;
    protected currentTotalBetDivider: number;
    protected allowedTotalBets: number[];
    protected locale: any;
    init(config: GameWrapperConfig): void;
    setUnsettledTicketExists(ticketExists: boolean): void;
    applyCurrencyLocaleOverride(currencyCode?: string): Currency;
    formatCurrency(value: number, trimFraction?: boolean, currencyCode?: string): string;
    formatNumber(value: number, trimFraction?: boolean): string;
    updateLoadingProgress(progress: number): void;
    muteSound(mute: boolean): void;
    showInfoMessage(scenario: string, message?: string): Promise<void>;
    handleRgsError(reason: RgsError): void;
    handleReplayStarted(): Promise<void>;
    handleReplayFinished(): void;
    protected registerPlugins(): void;
    protected handleContextBalanceUpdate(rgs: RgsAdapter<Rgs>, data: AnyObject): Promise<void>;
    protected handleNewRequest(host: any, data: AnyObject): Promise<void>;
    protected addBonusHeader(xmlHttp: XMLHttpRequest): void;
    protected handleErrorInAutoplay(autoplay: Autoplay, data: AnyObject): Promise<void>;
    protected intializeRgsConfigParams(): Promise<void>;
    protected findActiveBonus(bonuses: any): void;
    protected handleBonusRounds(): void;
    calculateBetLevel(totalBets: number | number[], totalBetDivider: number): number | number[];
    calculateTotalBets(): number[];
    protected finishBonusOffer(reason: BonusOfferFinishReason): void;
    protected isBetAvailable(rgs: RgsAdapter<Rgs>, bet: number | number[]): boolean;
    protected getLimitsForBet(rgs: RgsAdapter<Rgs>, bet: number | number[]): StakeLimits;
    protected setEventHandlers(): void;
}
export {};
