import GameWrapper, { GameWrapperConfig } from '../../GameWrapper';
import { RgsError } from '../../rgs/RgsTypes';
import { Dictionary } from '../../UtilTypes';
import { DefaultIntegrationLogic } from '../default-integration-logic';
import { Balance, OxtError, OxtMessage } from './oxt-types';
declare global {
    interface Window {
        clientAPI: any;
    }
}
export declare class OxtIntegrationLogic extends DefaultIntegrationLogic {
    protected config: GameWrapperConfig;
    private currentBalance;
    private currentStake;
    private beginOfRoundMode;
    private endOfRoundMode;
    private currentMode;
    private handleErrorMessagesInGame;
    private promoRounds;
    private regulatoryMessages;
    private accountInfo;
    private isSoundMuted;
    private lobbyPause;
    private bottomConfig;
    private oxtConfigPath;
    private lang;
    clientApiLibary: string;
    isLobbyActive: boolean;
    gameWrapper: GameWrapper;
    balanceSyncronized: Promise<void | unknown>;
    init(config: GameWrapperConfig, overrides?: Dictionary): void;
    disableRealityCheck(): void;
    publishInitSoundStatus(isSoundMuted: boolean): void;
    getDataFromjwt(): void;
    private loadGameManager;
    private resolveOnInit;
    private resolveOnConfig;
    private subscribeToPauseGame;
    private subscribeToResumeGame;
    private subscribeToAudioEnable;
    private subscribeToAudioDisable;
    private subscribeToAutoplayStop;
    private subscribeToQuickSpin;
    private subscribeToHelp;
    private subscribeToPaytable;
    private subscribeToAccountInfoUpdate;
    private updateConfig;
    private subscribeToBalanceUpdates;
    private subscribeToOxtEvents;
    private subscribeToSoundUpdates;
    private subscribeToWrapperEvents;
    handleErrorMessages(): void;
    private mapParameters;
    getCurrentBalance(): Balance;
    setCurrentBalance(balance: Balance): void;
    showError(code: number, message: string, action?: () => any): void;
    showOxtMessage(message: OxtMessage): void;
    handleOxtRgsError(reason: RgsError): void;
    handleRgsError(reason: RgsError): void;
    publishGameClose(): void;
    updateLoadingProgress(progress: number): void;
    muteSound(mute: boolean): void;
    confirmGameInitialized(): Promise<any>;
    publishLoadingStart(): void;
    publishLoadingFinished(): void;
    publishSoundOn(soundOn: boolean): void;
    initEnvironmentValues(): void;
    publishError(errorData: OxtError): void;
    sendGameAction(action: string, data: any): void;
    redirectToLobby(): void;
    publishWrapperEvent(eventName: string, data: any): void;
    protected subscribeToBalanceSync(): void;
    private resolveOnBalanceSync;
    private subscribeToUpdateGameInfo;
}
