import { UIInterface, UIConfig, BottomBarConfig, TopBarConfig } from './UITypes';
import { CapabilitiesHost } from './CapabilitiesHost';
import GameWrapper from './GameWrapper';
import SimpleFlowAdapter from './rgs/SimpleFlowApi';
import ScratchAdapter from './rgs/ScratchApi';
import MessageDialog from './MessageDialog';
import AutoplayDialog from './autoplay/AutoplayDialog';
import { Splash } from './ui/Splash';
import Overlay from './ui/Overlay';
export default class EmbeddedUI extends CapabilitiesHost implements UIInterface {
    element: HTMLElement;
    overlay: Overlay;
    splash: Splash;
    protected gameWrapper: GameWrapper;
    protected internalAssetsLoaded: boolean;
    protected isReadyFired: boolean;
    protected turbo: boolean;
    protected isWinCapped: boolean;
    protected isSoundMuted: boolean;
    messageDialog: MessageDialog;
    protected helpDialog: HTMLElement;
    protected autoplayDialog: AutoplayDialog;
    protected settingsDialog: HTMLElement;
    protected topBar: HTMLElement;
    protected bottomBar: HTMLElement;
    protected bottomBarSoundButton: HTMLElement;
    protected topBarSoundButton: HTMLElement;
    protected gameTitle: HTMLElement;
    protected autoButton: HTMLElement;
    protected infoBar: HTMLElement;
    protected modeLabel: HTMLDivElement;
    protected date: HTMLDivElement;
    protected clock: HTMLDivElement;
    protected balanceLabel: HTMLSpanElement;
    protected netLabel: HTMLSpanElement;
    protected bonusRoundsLabel: HTMLSpanElement;
    protected betLabel: HTMLSpanElement;
    protected winAmountLabel: HTMLSpanElement;
    protected bonusRoundsItem: HTMLLIElement;
    ready: Promise<unknown>;
    constructor(content: HTMLElement | string, parent: HTMLElement | string, gameWrapper: GameWrapper, config?: UIConfig);
    protected setupTopBar(config: TopBarConfig | undefined): HTMLElement;
    protected setupBottomBar(config: BottomBarConfig | undefined): HTMLElement;
    protected updateBetLabels(bet: any): void;
    showElements(show: boolean, elementName: string): void;
    changeSoundStatus(soundOn: boolean): void;
    attachRgs(rgs: ScratchAdapter | SimpleFlowAdapter<any>, params: any): void;
    updateMode(): void;
    setTitle(name: string): void;
    pauseGame(): void;
    resumeGame(): void;
    updateStrings(): void;
    setLoaderProgress(progress: number): void;
    hideSplash(force?: boolean): Promise<void>;
    updateBet(bet: number): void;
    clearWinAmount(): void;
    updateWinAmount(): void;
    updateNetAmount(): void;
    showAutoplayDialog(): void;
    goToLobby(): Promise<void>;
    showMessage(message: string | {
        title?: string;
        subtitle?: string;
        text?: string;
    }): void;
    muteSound(mute: boolean): void;
    setVolume(volume: number): void;
    setTurbo(turbo: boolean): void;
    protected setupAutoplayDialog(): AutoplayDialog;
    showElementsTopBar(show: boolean, className: string): void;
    showElementsBottomBar(show: boolean, className: string): void;
}
