import './util/Polyfill';
import { CapabilitiesHost } from './CapabilitiesHost';
import { GameClientConfig } from './GameClient';
import { ConstructorOf, Dictionary, StringDictionary, Currency, CurrencyConfig, CurrencyDisplay } from './UtilTypes';
import { ScratchcardRgs } from './rgs/ScratchApi';
import { SlotRgs } from './rgs/SlotApi';
import { KenoRgs } from './rgs/KenoApi';
import { CardsRgs } from './rgs/CardsApi';
import { TableGameRgs } from './rgs/TableGameApi';
import RealityCheck from './RealityCheck';
import Autoplay, { AutoplayWrapperConfig } from './autoplay/Autoplay';
import Fullscreen, { FullscreenConfig } from './overlay/Fullscreen';
import { PostMessageConfig } from './WindowMessaging';
import { MessageDialogConfig } from './MessageDialog';
import { RgsAdapter } from './rgs/RgsAdapter';
import { Rgs } from './rgs/Rgs';
import { StakeLimits } from './rgs/RgsTypes';
import { IntegrationLogicInterface } from './integrations/integration-logic';
import { UIConfig, UIInterface } from './UITypes';
export declare const VERSION = "[VI]{version}[/VI]";
export declare const BUILD_DATE = "[VI]{date}[/VI]";
export declare let actions: {
    autoplay: FunctionConstructor;
    play: FunctionConstructor;
    turbo: FunctionConstructor;
};
export declare const MAX_PURCHASE_ATTEMPTS = 3;
export declare let fullscreen: Fullscreen;
export declare let params: StringDictionary;
export interface GameWrapperConfig {
    gameId: string | string[];
    gameType: 'slot' | 'keno' | 'fixed-odds' | 'scratchcard' | 'cards' | 'table-game';
    gameName?: string;
    metaGameId?: string;
    rpcUrl?: string;
    content?: HTMLElement | string;
    container?: HTMLElement | string;
    fullscreenContent?: HTMLElement | string;
    langPath?: string;
    jurisdictionPath?: string;
    currencyData?: string;
    currencyDisplay?: CurrencyDisplay;
    isSocialCasinoMode?: boolean;
    useCompactNotation?: boolean;
    ui?: UIConfig;
    messages?: boolean | MessageDialogConfig;
    autoplay?: AutoplayWrapperConfig;
    postMessage?: boolean | PostMessageConfig;
    fullscreen?: boolean | FullscreenConfig;
    fullscreenAfterLoad?: boolean;
    forceOrientation?: 'landscape' | 'portrait';
    enableJackpotNotifications?: boolean;
    jackpotReconnectIntervals?: number[];
    isCdnSupportEnabled?: boolean;
    enableBonusDeferral?: boolean;
    readonly gameConfig: GameClientConfig;
    commonUIPosition?: 'left' | 'right' | 'centre';
    gcmConfigPrefix?: string;
    showLogo?: boolean;
    isIosPlatform?: boolean;
    glUtilPath?: string;
    rsiLobbyRestriction?: boolean;
    mainUI?: boolean;
    params?: StringDictionary;
}
type ApiSelector = ((config: GameWrapperConfig) => typeof ScratchcardRgs | typeof SlotRgs | typeof KenoRgs | typeof CardsRgs | typeof TableGameRgs);
export declare function setApiSelector(func: ApiSelector): void;
export declare function getApiSelector(): (config: GameWrapperConfig) => typeof ScratchcardRgs | typeof SlotRgs | typeof KenoRgs | typeof CardsRgs | typeof TableGameRgs;
export declare function getParam(option: string): string;
export default class GameWrapper extends CapabilitiesHost {
    config: GameWrapperConfig;
    langPath: string;
    jurisdictionPath: string;
    languageConfig: string;
    languageMap?: {
        [from: string]: string;
    };
    rgs: RgsAdapter<Rgs>;
    autoplay: Autoplay;
    ui: UIInterface;
    uiClass: ConstructorOf<UIInterface>;
    integration: IntegrationLogicInterface;
    realityCheck: RealityCheck;
    state: 'active' | 'paused' | 'error';
    gameMode: string;
    gameName: string;
    stake: number;
    winAmount: number;
    netAmount: number;
    currency: Currency;
    currencyConfig: CurrencyConfig;
    private _resolveInitialized;
    private _resolveReady;
    initialized: Promise<void>;
    ready: Promise<void>;
    jurisdictionReady: Promise<void>;
    startTime: number;
    unsupportedLanguage: boolean;
    lobbyLanguage: string;
    documentLanguage: string;
    gameJurisdiction: JSON;
    enableLangAttribute: boolean;
    private pauseQueue;
    constructor(config?: GameWrapperConfig | string, overrides?: Dictionary);
    setup(config: GameWrapperConfig | string, overrides?: Dictionary): Promise<void>;
    private validateConfig;
    private getLanguageMap;
    private envSetup;
    private initIntegration;
    private loadJurisdiction;
    private applySetup;
    init(config: GameWrapperConfig): Promise<void>;
    getConfig(): GameWrapperConfig;
    getGameConfig(): GameClientConfig;
    setCurrency(currencyCode: string): void;
    formatCurrency(value: number, trimFraction?: boolean, currencyCode?: string): string;
    formatNumber(value: number, trimFraction?: boolean): string;
    setName(name: string): void;
    setBetStops(betConfig: StakeLimits): void;
    getBet(): number;
    setBet(bet: number): void;
    getWinAmount(): number;
    getNetAmount(): number;
    gameReady(): void;
    pauseGame(): void;
    resumeGame(): void;
    unpause(): void;
    startReplay(ticketId?: string): Promise<any>;
    endReplay(): void;
    isDemoGameMode(): boolean;
    isHistoryGameMode(): boolean;
    getGameMode(): "history" | "demo" | "realmoney";
    updateGameMode(): void;
    getElapsedTime(): {
        hours: number;
        minutes: number;
        seconds: number;
    };
    getJurisdiction(): JSON;
    private subscribeToJackpotNotifications;
    getVersionedResource(resourceUrl?: string, version?: number): string;
}
export {};
