import _GameWrapper, { GameWrapperConfig } from './GameWrapper';
import { Dictionary } from './UtilTypes';
export declare let GameWrapper: typeof _GameWrapper;
export declare let instance: _GameWrapper;
export declare let initialized: Promise<void>;
export declare let ready: Promise<void>;
export declare let rgs: import("./rgs/RgsAdapter").RgsAdapter<import("./rgs/Rgs").Rgs>;
export declare let autoplay: import("./autoplay/Autoplay").default;
export declare let ui: import("./UITypes").UIInterface;
export declare let realityCheck: import("./RealityCheck").default;
export declare let state: "error" | "active" | "paused";
export declare let gameMode: string;
export declare let setup: (config: GameWrapperConfig | string, overrides?: Dictionary) => Promise<void>;
export declare let init: (config: GameWrapperConfig) => Promise<void>;
export declare let getConfig: any;
export declare let getGameConfig: any;
export declare let setCurrency: any;
export declare let formatCurrency: any;
export declare let formatNumber: any;
export declare let setName: any;
export declare let getBet: any;
export declare let setBet: any;
export declare let startReplay: any;
export declare let endReplay: any;
export declare let getNetAmount: any;
export declare let getElapsedTime: any;
export declare let getJurisdiction: any;
export declare let getWinAmount: any;
export declare let gameReady: any;
export declare let on: any;
export declare let once: any;
export declare let off: any;
export { BUILD_DATE, VERSION, MAX_PURCHASE_ATTEMPTS, fullscreen, setApiSelector, getApiSelector, getParam, params, actions } from './GameWrapper';
