import { CapabilitiesHost } from './CapabilitiesHost';
import Overlay from "./ui/Overlay";
import MessageDialog from "./MessageDialog";
import ScratchAdapter from "./rgs/ScratchApi";
import AutoplayDialog from "./autoplay/AutoplayDialog";
import SimpleFlowAdapter from "./rgs/SimpleFlowApi";
import GameWrapper from "./GameWrapper";
import { Splash } from './ui/Splash';
import { UIInterface, TopBarConfig, BottomBarConfig, UIConfig } from './UITypes';
export default class WrapperUI extends CapabilitiesHost implements UIInterface {
    element: HTMLElement;
    overlay: Overlay;
    splash: Splash;
    protected gameWrapper: GameWrapper;
    protected isWinCapped: boolean;
    protected isReady: boolean;
    protected turbo: boolean;
    protected isBonusRoundsEnabled: boolean;
    protected isSoundMuted: boolean;
    protected demoShowsModeOnly: boolean;
    messageDialog: MessageDialog;
    protected helpDialog: HTMLElement;
    protected autoplayDialog: AutoplayDialog;
    protected settingsDialog: HTMLElement;
    protected topBar: HTMLElement;
    protected bottomBar: HTMLElement;
    protected bonusToggleBtn: HTMLElement;
    protected bonusToggleBtnContainer: HTMLElement;
    protected bottomBarSoundButton: HTMLElement;
    protected topBarSoundButton: HTMLElement;
    protected gameTitle: HTMLElement;
    protected autoButton: HTMLElement;
    protected infoBar: HTMLElement;
    protected modeLabel: HTMLDivElement;
    protected date: HTMLDivElement;
    protected clock: HTMLDivElement;
    protected balanceLabel: HTMLSpanElement;
    protected netLabel: HTMLSpanElement;
    protected bonusRoundsLabel: HTMLSpanElement;
    protected betLabel: HTMLSpanElement;
    protected winAmountLabel: HTMLSpanElement;
    protected bonusRoundsItem: HTMLLIElement;
    ready: Promise<unknown>;
    constructor(content: HTMLElement | string, parent: HTMLElement | string, gameWrapper: GameWrapper, config?: UIConfig);
    protected setupTopBar(config: TopBarConfig | undefined): HTMLElement;
    protected setupHelp(): HTMLElement;
    protected setupAutoplayDialog(): AutoplayDialog;
    changeSoundStatus(soundOn: boolean): void;
    protected setupBottomBar(config: BottomBarConfig | undefined): HTMLElement;
    attachRgs(rgs: ScratchAdapter | SimpleFlowAdapter<any>, params: any): void;
    pauseGame(): void;
    resumeGame(): void;
    updateMode(): void;
    setTitle(name: string): void;
    updateStrings(): void;
    setLoaderProgress(progress: number): void;
    hideSplash(force?: boolean): Promise<void>;
    updateBet(bet: any): void;
    protected updateBetLabels(bet: any): void;
    clearWinAmount(): void;
    updateWinAmount(): void;
    updateNetAmount(): void;
    showAutoplayDialog(): void;
    goToLobby(): Promise<any>;
    showMessage(message: string | {
        title?: string;
        subtitle?: string;
        text?: string;
    }): void;
    muteSound(mute: boolean): void;
    setVolume(volume: number): void;
    setTurbo(turbo: boolean): void;
    showElementsTopBar(show: boolean, className: string): void;
    showElementsBottomBar(show: boolean, className: string): void;
}
