import { FormatCurrencyOptions } from './UtilTypes';
export declare function createElement(tag: any, id?: string, classList?: any[], children?: Node[]): HTMLElement;
export declare function createInputElement(type: string): HTMLInputElement;
export declare function createEvent(type: string, data?: any): CustomEvent<{
    data: any;
}>;
export declare function isTrue(value: any): boolean;
export declare function isFalse(value: any): boolean;
export declare function isString(value: any): boolean;
export declare function formatCurrency(value: number, options: FormatCurrencyOptions): string;
export declare function formatNumber(value: number, locale?: string, trimFraction?: boolean): string;
export declare function isAppleWebView(): boolean;
export declare function isLocallyDeployed(): boolean;
export declare function applyAppleWebViewFix(): void;
export declare function getChildTagStringValue(doc: Document | Element, qualifiedName: string): string;
export declare function getChildTagNumberValue(doc: Document | Element, qualifiedName: string): number;
export declare function getChildTagBooleanValue(doc: Document | Element, qualifiedName: string): boolean;
export declare function isNullString(value: string): boolean;
export declare function isNullOrEmptyString(value: string): boolean;
export declare function isNullNumber(value: number): boolean;
export declare function isNullOrZeroNumber(value: number): boolean;
export declare function isNullOrFiniteNumber(value: number): boolean;
export declare function isRegularNumber(value: number): boolean;
export declare function isNullBoolean(value: boolean): boolean;
export declare function isNull(value: any): boolean;
